import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import MyProfilePicture from "./components/MyProfilePicture";

export const metadata: Metadata = {
  title: "Grim's Blog",
  description: "Generated by Grim Reaper",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <Navbar />
        <MyProfilePicture />
        {children}
      </body>
    </html>
  );
}
